package Graphics;

import Logica.FabricaPersonajes;
import Logica.Personaje;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Camilo Garcia
 */
public class MostrarPersonajes extends javax.swing.JFrame {

    private ArrayList<String> nombres = new ArrayList<>();
    private ArrayList<Personaje> personajes = new ArrayList<>();
    private String type;

    /**
     * Creates new form MostrarPersonajes
     * @param nombres
     * @param type
     */
    // constructor que muestra los personajes creados
    public MostrarPersonajes(ArrayList nombres, String type) {
        this.nombres = nombres;
        this.type = type;      
        iniciarPersonajes();
        initComponents();
        AgregarPersonajes();
    }

    public MostrarPersonajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    // Se crea un objeto de la fabrica de personajes y se retorna un arraylist con todos los personajes creados
    public void iniciarPersonajes() {
        FabricaPersonajes getPersonajes = new FabricaPersonajes(type, nombres);
        personajes = getPersonajes.getPersonajes();
    }

    // se establecen las medidas de la interfaz y se agrega cada personaje
    private void AgregarPersonajes() {

        this.setSize(250 * nombres.size(), 600);

        jLabel1.setLayout(new GridLayout(1, nombres.size()));
        for (int i = 0; i < nombres.size(); i++) {
            javax.swing.JLabel personaje = new javax.swing.JLabel();
            personaje.setLayout(new GridLayout(2, 1));
            javax.swing.JLabel texto1 = new javax.swing.JLabel();
            javax.swing.JLabel imagen1 = new javax.swing.JLabel();
            ImageIcon imagenPersonaje = new ImageIcon("src/Imagenes/" + this.type + ".png");

            ImageIcon imagenArma = new ImageIcon("src/Imagenes/" + personajes.get(i).getArma().getNombre() + ".png");

            texto1.setText("<html><body> Nombre: " + personajes.get(i).getNombre() + "<br> Genero: " + personajes.get(i).getGenero()
                    + "<br> Personalidad: " + personajes.get(i).getPersonalidad() + "<br><br> ARMA: " + personajes.get(i).getArma().getNombre()
                    + "<br> Daño: " + personajes.get(i).getArma().getDanio() + "<br> Resistencia: " + personajes.get(i).getArma().getResistencia()
                    + "<br><br> ESTADISTICAS: <br> Fuerza: " + personajes.get(i).getEst().getFuerza() + "<br> Maná: " + personajes.get(i).getEst().getMana()
                    + "<br> Resistencia: " + personajes.get(i).getEst().getResitencia() + "<br> Velocidad: " + personajes.get(i).getEst().getVelocidad() + "</body></html>");
            texto1.setIcon(imagenArma);

            imagen1.setIcon(imagenPersonaje);

            personaje.add(texto1);
            personaje.add(imagen1);
            personaje.setSize(this.getWidth() / nombres.size(), this.getHeight());
            jLabel1.add(personaje);
        }

    }
}
