/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import java.util.ArrayList;

/**
 *
 * @author User
 */
public class PedirDatosPersonaje extends javax.swing.JFrame {
    private ArrayList<String> nombres = new ArrayList<String>();
    /**
     * Creates new form PedirDatosPersonaje
     */
    public PedirDatosPersonaje() {
        initComponents();
        iniciar_campos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jComboTipoPersonaje = new javax.swing.JComboBox<>();
        jLabelCantidad = new javax.swing.JLabel();
        jComboCantidad = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenida.setText("Bienvenido, escoja el personaje que desea");

        jComboTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barbaro", "Arquera", "Duende", "Gigante", "Duende" }));

        jLabelCantidad.setText("Ingrese la cantidad de personajes");

        jComboCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboCantidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboCantidadItemStateChanged(evt);
            }
        });

        jLabelNombre.setText("Ingrese nombre 1");

        jButtonAñadir.setText("Ingresar Nombre");
        jButtonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAñadirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jComboTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jComboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonAñadir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabelNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextNombre)
                    .addComponent(jLabelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelCantidad)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelBienvenida)
                .addGap(18, 18, 18)
                .addComponent(jComboTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre)
                .addGap(12, 12, 12)
                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAñadir)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabelBienvenida.getAccessibleContext().setAccessibleName("jLabelBienbenida");
        jComboTipoPersonaje.getAccessibleContext().setAccessibleName("jComboTipoPersonaje");
        jLabelCantidad.getAccessibleContext().setAccessibleName("jLabelCantidad");
        jComboCantidad.getAccessibleContext().setAccessibleName("jComboCantidad");
        jLabelNombre.getAccessibleContext().setAccessibleName("jLabelNombre");
        jTextNombre.getAccessibleContext().setAccessibleName("jTextNombre");
        jButtonAñadir.getAccessibleContext().setAccessibleName("jButtomAñadir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCantidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboCantidadItemStateChanged
        if(jComboCantidad.getSelectedItem()!=null){
            jButtonAñadir.setVisible(true);
            jLabelNombre.setVisible(true);
            jTextNombre.setVisible(true);
        }
    }//GEN-LAST:event_jComboCantidadItemStateChanged

    private void jButtonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAñadirMouseClicked
        
        if(nombres.size() >= Integer.parseInt((String)jComboCantidad.getSelectedItem())){
            //en caso de que ya esten todos los nombres
        }else{
            jLabelNombre.setText("Ingrese nombre "+(nombres.size()+1));
        }
    }//GEN-LAST:event_jButtonAñadirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedirDatosPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedirDatosPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedirDatosPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedirDatosPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedirDatosPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JComboBox<String> jComboCantidad;
    private javax.swing.JComboBox<String> jComboTipoPersonaje;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables

    public void iniciar_campos(){
        jButtonAñadir.setVisible(false);
        jLabelNombre.setVisible(false);
        jTextNombre.setVisible(false);
        jComboCantidad.setSelectedItem(null);
        System.out.println(nombres.size());
    }
}
