package Graphics;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PedirDatosPersonaje extends javax.swing.JFrame {
    private ArrayList<String> nombres = new ArrayList<String>();
    /**
     * Creates new form PedirDatosPersonaje
     */
    public PedirDatosPersonaje() {
        initComponents();
        iniciar_campos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jComboTipoPersonaje = new javax.swing.JComboBox<>();
        jLabelCantidad = new javax.swing.JLabel();
        jComboCantidad = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenida.setText("Bienvenido, escoja el personaje que desea");

        jComboTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barbaro", "Arquera", "Duende", "Gigante", "Mago" }));

        jLabelCantidad.setText("Ingrese la cantidad de personajes");

        jComboCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboCantidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboCantidadItemStateChanged(evt);
            }
        });

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Ingrese nombre 1");
        jLabelNombre.setToolTipText("");

        jButtonAñadir.setText("Ingresar Nombre");
        jButtonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAñadirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNombre)
                    .addComponent(jLabelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelCantidad)))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jComboTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jComboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonAñadir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelBienvenida)
                .addGap(18, 18, 18)
                .addComponent(jComboTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre)
                .addGap(12, 12, 12)
                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAñadir)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabelBienvenida.getAccessibleContext().setAccessibleName("jLabelBienbenida");
        jComboTipoPersonaje.getAccessibleContext().setAccessibleName("jComboTipoPersonaje");
        jLabelCantidad.getAccessibleContext().setAccessibleName("jLabelCantidad");
        jComboCantidad.getAccessibleContext().setAccessibleName("jComboCantidad");
        jLabelNombre.getAccessibleContext().setAccessibleName("jLabelNombre");
        jTextNombre.getAccessibleContext().setAccessibleName("jTextNombre");
        jButtonAñadir.getAccessibleContext().setAccessibleName("jButtomAñadir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCantidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboCantidadItemStateChanged
        if(jComboCantidad.getSelectedItem()!=null){
            jButtonAñadir.setVisible(true);
            jLabelNombre.setVisible(true);
            jTextNombre.setVisible(true);
            jComboTipoPersonaje.setEnabled(false);
            jComboCantidad.setEnabled(false);
        }
    }//GEN-LAST:event_jComboCantidadItemStateChanged

    private void jButtonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAñadirMouseClicked
        
        if(nombres.size() < Integer.parseInt((String)jComboCantidad.getSelectedItem())){
            if("".equals(jTextNombre.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un nombre");
            }else{
                nombres.add(jTextNombre.getText());
                jTextNombre.setText("");
                if(nombres.size() < Integer.parseInt((String)jComboCantidad.getSelectedItem())){
                    jLabelNombre.setText("Ingrese nombre "+(nombres.size()+1));
                }else{
                    jTextNombre.setVisible(false);
                    jLabelNombre.setText("Todos los nombres ingresados");
                    jButtonAñadir.setText("Enviar");
                }
            }
        }else{
            jButtonAñadir.setVisible(false);
            MostrarPersonajes mos = new MostrarPersonajes(nombres,(String)jComboTipoPersonaje.getSelectedItem());
            mos.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAñadirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JComboBox<String> jComboCantidad;
    private javax.swing.JComboBox<String> jComboTipoPersonaje;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables

    public void iniciar_campos(){
        jButtonAñadir.setVisible(false);
        jLabelNombre.setVisible(false);
        jTextNombre.setVisible(false);
        jComboCantidad.setSelectedItem(null);
        System.out.println(nombres.size());
    }
}
